In [1]:
# import googletrans
import time
# from googletrans import Translator
# import nltk
import pandas as pd
from tqdm import tqdm

Preprocessing to ensure both TCN and EN train dataset are following same set of categories

In [2]:
cleaned_train_en = pd.read_csv('./preprocessed/cleaned_train_en.csv')
cleaned_train_en

,product_title,category,processed_title
0,Recollections Color Splash Clear Stamps & Stencil,Hobbies & Stationery,recollections color splash clear stamps stencil
1,"soap,lotion scrub set 400",Health & Personal Care,soap lotion scrub set
2,Spigen Galaxy S10e Case Tough Armor Gunmetal,Mobile Accessories,spigen galaxy case tough armor gunmetal
3,Acrylic Lanalon Bright Red,Hobbies & Stationery,acrylic lanalon bright red
4,303 FLAT SHEET/Blanket 100% cotton,Home & Living,flat sheet blanket cotton
...,...,...,...
499995,rocker arm roller racing mio,Motors,rocker arm roller racing mio
499996,Secosana (preloved bag),Women's Bags,secosana preloved bag
499997,jag bag,Women's Bags,jag bag
499998,Baby wipes 15 sheets (Alcohol and Paraben Free...,Babies & Kids,baby wipes sheets alcohol and paraben free san...
499999,PRE-LOVED ORIGINAL GREEN FINO BAG,Women's Bags,pre loved original green fino bag

In [3]:
cleaned_train_tcn = pd.read_csv('./preprocessed/cleaned_train_tcn.csv')
cleaned_train_tcn

,product_title,category,product_title_clean,product_title_tokenized
0,Gucci Gucci Guilty Pour Femme Stud Edition 罪愛女...,Health & Beauty,罪愛女性淡香水限量版,罪愛 女性 淡 香水 限量版
1,（二手）PS4 GTA 5 俠盜獵車手5 Grand Theif Auto V繁體 中文版,Game Kingdom,二手俠盜獵車手繁體中文版,二手 俠盜 獵車手 繁體 中文版
2,百獸卡,Life & Entertainment,百獸卡,百獸 卡
3,nac nac活氧全效柔衣素,Mother & Baby,活氧全效柔衣素,活氧全 效柔 衣素
4,#Nike耐吉官方F.C. 男子足球長褲新款標準型 拒水 拉鏈褲腳\nCD0557,Men's Apparel,耐吉官方男子足球長褲新款標準型拒水拉鏈褲腳,耐吉 官方 男子 足球 長 褲 新款 標準 型 拒水 拉鏈 褲腳
...,...,...,...,...
499995,Dress,Women's Apparel,NaN,NaN
499996,Lilian Lin,Food & Beverages,NaN,NaN
499997,77 抹茶杏仁乳加 77乳加 減甜 大人味 大人的77 宇治抹茶 杏仁 宇治抹茶杏仁 抹茶 ...,Food & Beverages,抹茶杏仁乳加乳加減甜大人味大人的宇治抹茶杏仁宇治抹茶杏仁抹茶,抹 茶 杏仁 乳加 乳加 減甜 大人 味 大人 的 宇治 抹 茶 杏仁 宇治 抹 茶 杏仁 抹 茶
499998,Panasonic 國際牌 電動 牙刷頭 (EW-DM81 專用刷頭) WEW0974-W,Home Electronic,國際牌電動牙刷頭專用刷頭,國際牌 電動 牙刷 頭專用 刷頭
499999,正品 新款紅眼 戰神哈奴曼手鐲 哈魯曼手環 戰神哈努曼 龍波雨水 新款紅眼 提升勇氣自信心 ...,Life & Entertainment,正品新款紅眼戰神哈奴曼手鐲哈魯曼手環戰神哈努曼龍波雨水新款紅眼提升勇氣自信心擊退小人招財已開光加持,正品 新款 紅眼 戰神哈 奴曼 手鐲 哈魯曼手 環戰 神哈 努曼 龍波 雨水 新款 紅眼 提...

In [4]:
category_tcn = cleaned_train_tcn['category'].unique()
category_en = cleaned_train_en['category'].unique()

print(category_tcn)
print(len(category_tcn))

print(category_en)
print(len(category_en))

['Health & Beauty' 'Game Kingdom' 'Life & Entertainment' 'Mother & Baby'
 "Men's Apparel" "Women's Apparel" 'Women Bags' 'Women Shoes'
 'Home & Living' 'Everything Else' 'Hardware & 3C'
 "Men's Bags& Accessories" 'Sports & Outdoors' 'Helpbuy' 'Men Shoes'
 'Books' 'Motors' 'Home Electronic' 'Food & Beverages' 'Mobile & Gadgets'
 'Women Accessories' 'Pets' 'Tickets & Services' nan]
24
['Hobbies & Stationery' 'Health & Personal Care' 'Mobile Accessories'
 'Home & Living' "Women's Apparel" 'Women Shoes' 'Babies & Kids'
 'Women Accessories' 'Toys, Games & Collectibles' 'Groceries' 'Motors'
 'Makeup & Fragrances' "Women's Bags" "Men's Apparel" 'Pet Care'
 "Men's Bags & Accessories" 'Sports & Travel' 'Men Shoes' 'Gaming'
 'Laptops & Computers' 'Home Entertainment' 'Mobiles & Gadgets' 'Cameras'
 'Home Appliances' 'Consumer Electronics' ' Games & Collectibles"'
 'Digital Goods & Vouchers']
27

In [5]:
temp = list(set(category_en)-set(category_tcn))
same_category = list(set(category_en)-set(temp))
print(same_category)
print(len(same_category))

['Men Shoes', "Women's Apparel", "Men's Apparel", 'Home & Living', 'Motors', 'Women Shoes', 'Women Accessories']
7

In [6]:
filtered_train_en = cleaned_train_en.copy()
filtered_train_en = filtered_train_en[filtered_train_en['category'].isin(same_category)]
filtered_train_en

,product_title,category,processed_title
4,303 FLAT SHEET/Blanket 100% cotton,Home & Living,flat sheet blanket cotton
5,Korean Set,Women's Apparel,korean set
6,High-grade keychain,Home & Living,high grade keychain
7,【COD】Chanel Black/White Sneaker Shoes For Women,Women Shoes,cod chanel black white sneaker shoes for women
8,Cat eyeglasses,Women's Apparel,cat eyeglasses
...,...,...,...
499989,Bow Dress,Women's Apparel,bow dress
499991,COD Chic Style Topshop Dress,Women's Apparel,cod chic style topshop dress
499992,Colored Stripes Tops ST110,Women's Apparel,colored stripes tops
499993,ForMe REFORME Button Down Shirt (Pink),Women's Apparel,forme reforme button down shirt pink
499995,rocker arm roller racing mio,Motors,rocker arm roller racing mio

In [7]:
filtered_train_en[filtered_train_en['processed_title'].isna()]

                        product_title           category processed_title
895     aaappaareelllllllllasdad42eer    Women's Apparel             NaN
1329                          8010/1A      Home & Living             NaN
1517                           2for99    Women's Apparel             NaN
2596               Xtkgdf123Xtkgdf123      Men's Apparel             NaN
3029                    TLDCS000002FS    Women's Apparel             NaN
...                               ...                ...             ...
492381                           PC01    Women's Apparel             NaN
492485                       Top62839    Women's Apparel             NaN
497208                      qwerty123             Motors             NaN
497211                       E111593A  Women Accessories             NaN
498611                            699    Women's Apparel             NaN

[393 rows x 3 columns]

In [8]:
filtered_train_en.dropna(inplace=True)

In [9]:
filtered_train_en.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 207750 entries, 4 to 499995
Data columns (total 3 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   product_title    207750 non-null  object
 1   category         207750 non-null  object
 2   processed_title  207750 non-null  object
dtypes: object(3)
memory usage: 6.3+ MB

In [10]:
filtered_train_tcn = cleaned_train_tcn.copy()
filtered_train_tcn = filtered_train_tcn[filtered_train_tcn['category'].isin(same_category)]
filtered_train_tcn

,product_title,category,product_title_clean,product_title_tokenized
4,#Nike耐吉官方F.C. 男子足球長褲新款標準型 拒水 拉鏈褲腳\nCD0557,Men's Apparel,耐吉官方男子足球長褲新款標準型拒水拉鏈褲腳,耐吉 官方 男子 足球 長 褲 新款 標準 型 拒水 拉鏈 褲腳
5,火影忍者六道鸣人cos睡衣卡卡西宇智波佐助T恤二次元动漫短袖衣服,Women's Apparel,火影忍者六道鸣人睡衣卡卡西宇智波佐助恤二次元动漫短袖衣服,火影忍者 六道 鸣人 睡衣 卡卡 西宇智 波佐助 恤 二次元 动漫 短袖 衣服
9,【小拇指鞋坊】Adidas Superstar 80s DLX 金標 貝殼頭 白紅 時尚男女...,Women Shoes,小拇指鞋坊金標貝殼頭白紅時尚男女鞋板鞋時尚情侶鞋男鞋女鞋,小拇指 鞋坊 金標 貝殼頭 白紅時 尚 男女 鞋板 鞋 時尚 情侶 鞋 男鞋 女鞋
10,? 居家大推款?記憶棉枕護勁頸椎枕修復脊椎治頸椎專用枕頭女孕婦失眠保健理療枕,Home & Living,居家大推款記憶棉枕護勁頸椎枕修復脊椎治頸椎專用枕頭女孕婦失眠保健理療枕,居家 大 推款 記憶 棉枕護 勁 頸 椎 枕修 復 脊椎 治頸椎 專用 枕頭 女孕婦 失眠 ...
14,Kalita 炫彩細口手沖壺(桃紅/藍/黃),Home & Living,炫彩細口手沖壺桃紅藍黃,炫彩 細口手 沖 壺桃紅 藍 黃
...,...,...,...,...
499986,牙膏,Home & Living,牙膏,牙膏
499988,NY棒球外套,Women's Apparel,棒球外套,棒球 外套
499992,創意LED臺燈 學生學習燈 USB充電臺燈 充電小夜燈,Home & Living,創意臺燈學生學習燈充電臺燈充電小夜燈,創意 臺 燈學生 學習 燈 充電 臺 燈 充電小夜 燈
499994,男裝 夏季男裝青少年短袖t恤白色修身韓版圓領純棉上衣服半袖男夏潮流,Men's Apparel,男裝夏季男裝青少年短袖恤白色修身韓版圓領純棉上衣服半袖男夏潮流,男裝 夏季 男裝 青少年 短袖 恤 白色 修身 韓版圓 領純 棉上 衣服 半袖 男夏 潮流
499995,Dress,Women's Apparel,NaN,NaN

In [11]:
filtered_train_tcn[filtered_train_tcn['product_title_tokenized'].isna()]

,product_title,category,product_title_clean,product_title_tokenized
113,🐷Sa🐷,Women's Apparel,NaN,NaN
602,◾️ig:77. _____,Women's Apparel,NaN,NaN
787,Ak2200sup,Men's Apparel,NaN,NaN
818,Peifan Wu,Home & Living,NaN,NaN
1062,.,Women's Apparel,NaN,NaN
...,...,...,...,...
499050,CIAO CASE,Women Accessories,NaN,NaN
499118,Yiting,Women's Apparel,NaN,NaN
499711,Hsiao chips Tsen,Women's Apparel,NaN,NaN
499789,Fen,Women's Apparel,NaN,NaN
499995,Dress,Women's Apparel,NaN,NaN

In [12]:
filtered_train_tcn.dropna(inplace=True)

In [13]:
filtered_train_tcn.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 222952 entries, 4 to 499994
Data columns (total 4 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   product_title            222952 non-null  object
 1   category                 222952 non-null  object
 2   product_title_clean      222952 non-null  object
 3   product_title_tokenized  222952 non-null  object
dtypes: object(4)
memory usage: 8.5+ MB

In [14]:
filtered_train_tcn['product_title_tokenized']

4                          耐吉 官方 男子 足球 長 褲 新款 標準 型 拒水 拉鏈 褲腳
5                   火影忍者 六道 鸣人 睡衣 卡卡 西宇智 波佐助 恤 二次元 动漫 短袖 衣服
9                 小拇指 鞋坊 金標 貝殼頭 白紅時 尚 男女 鞋板 鞋 時尚 情侶 鞋 男鞋 女鞋
10        居家 大 推款 記憶 棉枕護 勁 頸 椎 枕修 復 脊椎 治頸椎 專用 枕頭 女孕婦 失眠 ...
14                                         炫彩 細口手 沖 壺桃紅 藍 黃
                                ...
499984    愛心款 自由 拼接 浴室 防滑 墊 浴室 防滑 墊 拼接 淋浴 墊 地 墊 隔水 墊 可 裁...
499986                                                   牙膏
499988                                                棒球 外套
499992                          創意 臺 燈學生 學習 燈 充電 臺 燈 充電小夜 燈
499994        男裝 夏季 男裝 青少年 短袖 恤 白色 修身 韓版圓 領純 棉上 衣服 半袖 男夏 潮流
Name: product_title_tokenized, Length: 222952, dtype: object

In [15]:
translation_result = []
translator= Translator()
for i in tqdm(range(len(filtered_train_tcn['product_title_tokenized']))):
    translation_result.append(translator.translate(filtered_train_tcn['product_title_tokenized'].iloc[i], dest='en', src='zh-tw').text)
    time.sleep(1)

  1%|▉                                                                     | 2997/222952 [7:10:54<527:05:22,  8.63s/it]

ConnectError: [WinError 10065] A socket operation was attempted to an unreachable host

In [20]:
len(translation_result)

2997

In [21]:
for i in tqdm(range(2997,len(filtered_train_tcn['product_title_tokenized']))):
    translation_result.append(translator.translate(filtered_train_tcn['product_title_tokenized'].iloc[i], dest='en', src='zh-tw').text)
    time.sleep(1)

  0%|                                                                           | 54/219955 [01:06<75:34:06,  1.24s/it]

ConnectError: [Errno 11004] getaddrinfo failed

In [22]:
len(translation_result)

3051

In [23]:
for i in tqdm(range(3051,len(filtered_train_tcn['product_title_tokenized']))):
    translation_result.append(translator.translate(filtered_train_tcn['product_title_tokenized'].iloc[i], dest='en', src='zh-tw').text)
    time.sleep(1)

  1%|▉                                                                        | 2652/219901 [56:03<76:31:49,  1.27s/it]

KeyboardInterrupt:

In [24]:
len(translation_result)

5704

In [25]:
for i in tqdm(range(5704,len(filtered_train_tcn['product_title_tokenized']))):
    translation_result.append(translator.translate(filtered_train_tcn['product_title_tokenized'].iloc[i], dest='en', src='zh-tw').text)

  0%|                                                                          | 283/217248 [01:13<15:37:33,  3.86it/s]

AttributeError: 'Translator' object has no attribute 'raise_Exception'

In [26]:
len(translation_result)

5987

In [27]:
translator.raise_Exception = True
for i in tqdm(range(5987,len(filtered_train_tcn['product_title_tokenized']))):
    translation_result.append(translator.translate(filtered_train_tcn['product_title_tokenized'].iloc[i], dest='en', src='zh-tw').text)

  0%|                                                                          | 284/216965 [01:20<17:02:27,  3.53it/s]

Exception: Unexpected status code "429" from ('translate.google.com',)

In [28]:
len(translation_result)

6271

In [29]:
translator.raise_Exception = True
for i in tqdm(range(6271,len(filtered_train_tcn['product_title_tokenized']))):
    translation_result.append(translator.translate(filtered_train_tcn['product_title_tokenized'].iloc[i], dest='en', src='zh-tw').text)
    time.sleep(0.5)

  5%|███▌                                                                  | 11174/216681 [2:23:52<44:06:00,  1.29it/s]

ConnectTimeout: _ssl.c:1114: The handshake operation timed out

In [30]:
len(translation_result)

17445

In [31]:
translator.raise_Exception = True
for i in tqdm(range(17445,len(filtered_train_tcn['product_title_tokenized']))):
    translation_result.append(translator.translate(filtered_train_tcn['product_title_tokenized'].iloc[i], dest='en', src='zh-tw').text)
    time.sleep(0.3)

 15%|██████████▎                                                           | 30445/205507 [7:13:47<41:34:18,  1.17it/s]

ReadTimeout: The read operation timed out

In [32]:
len(translation_result)

47890

In [33]:
translator.raise_Exception = True
for i in tqdm(range(47890,len(filtered_train_tcn['product_title_tokenized']))):
    translation_result.append(translator.translate(filtered_train_tcn['product_title_tokenized'].iloc[i], dest='en', src='zh-tw').text)
    time.sleep(0.2)

  8%|█████▎                                                                | 13136/175062 [1:52:30<23:06:49,  1.95it/s]

ReadTimeout: The read operation timed out

In [34]:
len(translation_result)

61026

In [35]:
translator.raise_Exception = True
for i in tqdm(range(61026,len(filtered_train_tcn['product_title_tokenized']))):
    translation_result.append(translator.translate(filtered_train_tcn['product_title_tokenized'].iloc[i], dest='en', src='zh-tw').text)
    time.sleep(0.2)

 13%|█████████▎                                                            | 21464/161926 [9:01:55<59:06:26,  1.51s/it]

ConnectError: [WinError 10065] A socket operation was attempted to an unreachable host

In [36]:
len(translation_result)

82490

In [37]:
translator.raise_Exception = True
for i in tqdm(range(82490,len(filtered_train_tcn['product_title_tokenized']))):
    translation_result.append(translator.translate(filtered_train_tcn['product_title_tokenized'].iloc[i], dest='en', src='zh-tw').text)
    time.sleep(0.2)

 11%|███████▍                                                              | 14944/140462 [2:34:02<21:33:46,  1.62it/s]

ConnectTimeout: _ssl.c:1114: The handshake operation timed out

In [38]:
len(translation_result)

97434

In [39]:
translator.raise_Exception = True
for i in tqdm(range(97434,len(filtered_train_tcn['product_title_tokenized']))):
    translation_result.append(translator.translate(filtered_train_tcn['product_title_tokenized'].iloc[i], dest='en', src='zh-tw').text)
    time.sleep(0.2)

  4%|███                                                                    | 5509/125518 [1:32:17<33:30:24,  1.01s/it]

ReadTimeout: The read operation timed out

In [40]:
len(translation_result)

102943

In [41]:
translator.raise_Exception = True
for i in tqdm(range(102943,len(filtered_train_tcn['product_title_tokenized']))):
    translation_result.append(translator.translate(filtered_train_tcn['product_title_tokenized'].iloc[i], dest='en', src='zh-tw').text)
    time.sleep(0.2)

 27%|██████████████████▊                                                   | 32191/120009 [5:37:04<15:19:32,  1.59it/s]

ConnectError: [WinError 10065] A socket operation was attempted to an unreachable host

In [42]:
len(translation_result)

135134

In [44]:
translator.raise_Exception = True
for i in tqdm(range(135134,len(filtered_train_tcn['product_title_tokenized']))):
    translation_result.append(translator.translate(filtered_train_tcn['product_title_tokenized'].iloc[i], dest='en', src='zh-tw').text)
    time.sleep(0.2)

  6%|████▎                                                                   | 5276/87818 [1:06:45<17:24:29,  1.32it/s]

ConnectError: [WinError 10054] An existing connection was forcibly closed by the remote host

In [45]:
len(translation_result)

140410

In [46]:
translator.raise_Exception = True
for i in tqdm(range(140410,len(filtered_train_tcn['product_title_tokenized']))):
    translation_result.append(translator.translate(filtered_train_tcn['product_title_tokenized'].iloc[i], dest='en', src='zh-tw').text)
    time.sleep(0.2)

 84%|████████████████████████████████████████████████████████████▌           | 69367/82542 [9:11:35<1:44:45,  2.10it/s]

ConnectError: [Errno 11001] getaddrinfo failed

In [47]:
len(translation_result)

209777

In [48]:
translator.raise_Exception = True
for i in tqdm(range(209777,len(filtered_train_tcn['product_title_tokenized']))):
    translation_result.append(translator.translate(filtered_train_tcn['product_title_tokenized'].iloc[i], dest='en', src='zh-tw').text)
    time.sleep(0.2)

100%|██████████████████████████████████████████████████████████████████████████| 13175/13175 [1:33:51<00:00,  2.34it/s]

In [49]:
len(translation_result)

222952

In [15]:
import numpy as np
# np.save("translation_result",translation_result)
translation_result = np.load("translation_result.npy")
translation_result.shape

(222952,)

In [16]:
translation_result[0]

"Niji official men's football trousers new standard refusal zipper trousers"

In [17]:
filtered_train_tcn['product_title_tokenized'].iloc[0]

'耐吉 官方 男子 足球 長 褲 新款 標準 型 拒水 拉鏈 褲腳'

In [18]:
filtered_train_en

,product_title,category,processed_title
4,303 FLAT SHEET/Blanket 100% cotton,Home & Living,flat sheet blanket cotton
5,Korean Set,Women's Apparel,korean set
6,High-grade keychain,Home & Living,high grade keychain
7,【COD】Chanel Black/White Sneaker Shoes For Women,Women Shoes,cod chanel black white sneaker shoes for women
8,Cat eyeglasses,Women's Apparel,cat eyeglasses
...,...,...,...
499989,Bow Dress,Women's Apparel,bow dress
499991,COD Chic Style Topshop Dress,Women's Apparel,cod chic style topshop dress
499992,Colored Stripes Tops ST110,Women's Apparel,colored stripes tops
499993,ForMe REFORME Button Down Shirt (Pink),Women's Apparel,forme reforme button down shirt pink
499995,rocker arm roller racing mio,Motors,rocker arm roller racing mio

In [19]:
import math
import re
from collections import Counter

WORD = re.compile(r"\w+")

def get_cosine(v1, v2):
    intersects = set(v1.keys()) & set(v2.keys())
    num = sum([v1[x] * v2[x] for x in intersects])
    sum1 = sum([v1[x] ** 2 for x in list(v1.keys())])
    sum2 = sum([v2[x] ** 2 for x in list(v2.keys())])
    den = math.sqrt(sum1) * math.sqrt(sum2)
    if not den:
        return 0.0
    else:
        return round(float(num) / den,3)

def text_to_vector(text):
    words = WORD.findall(text)
    return Counter(words)

In [20]:
all_sentences = filtered_train_en['processed_title']
all_sentences_vectors = []
for k in tqdm(range(len(all_sentences))):
    all_sentences_vectors.append(text_to_vector(all_sentences.iloc[k]))

100%|███████████████████████████████████████████████████████████████████████| 207750/207750 [00:05<00:00, 39795.27it/s]

In [21]:
all_sentences_vectors

[Counter({'flat': 1, 'sheet': 1, 'blanket': 1, 'cotton': 1}),
 Counter({'korean': 1, 'set': 1}),
 Counter({'high': 1, 'grade': 1, 'keychain': 1}),
 Counter({'cod': 1,
          'chanel': 1,
          'black': 1,
          'white': 1,
          'sneaker': 1,
          'shoes': 1,
          'for': 1,
          'women': 1}),
 Counter({'cat': 1, 'eyeglasses': 1}),
 Counter({'ati': 1, 'atihan': 1, 'costume': 1}),
 Counter({'teal': 1,
          'and': 1,
          'light': 1,
          'purple': 1,
          'crystal': 1,
          'dangle': 1,
          'drop': 1,
          'earrings': 1}),
 Counter({'onhand': 1, 'sleeveless': 1, 'crisscross': 1, 'top': 1}),
 Counter({'fashion': 1,
          'statement': 1,
          'necklace': 1,
          'the': 1,
          'walking': 1,
          'dead': 1}),
 Counter({'rachelle': 1, 'blouse': 1}),
 Counter({'ghia': 1, 'scoopback': 1}),
 Counter({'korean': 1, 'ladies': 1, 'strapless': 1, 'skirts': 1}),
 Counter({'motor': 1, 'start': 1, 'lowering': 1, 'crown': 1}),
 Counter({'big': 1, 'blouse': 1}),
 Counter({'black': 1, 'lacey': 1, 'dress': 1}),
 Counter({'cod': 1, 'hello': 1, 'kitty': 1, 'watch': 1, 'led': 1, 'black': 1}),
 Counter({'halter': 1, 'bandeau': 1, 'swimsuit': 1}),
 Counter({'way': 1, 'nursing': 1, 'breastfeeding': 1, 'tops': 1}),
 Counter({'brown': 1,
          'tweed': 1,
          'blazer': 1,
          'with': 1,
          'white': 1,
          'vertical': 1,
          'stripes': 1}),
 Counter({'quarts': 1,
          'wall': 1,
          'clock': 1,
          'w': 1,
          'free': 1,
          'battery': 1}),
 Counter({'osm': 1,
          'polo': 1,
          'sport': 1,
          'by': 1,
          'ralph': 1,
          'lauren': 1,
          'new': 1,
          'red': 1,
          'mens': 1}),
 Counter({'premium': 1,
          'gold': 1,
          'and': 1,
          'black': 1,
          'elegant': 1,
          'cutlery': 1,
          'set': 1,
          'stainless': 1}),
 Counter({'stance': 1,
          'nation': 1,
          'japan': 1,
          'keychain': 1,
          'car': 1,
          'accessories': 1}),
 Counter({'casual': 1, 'bodycon': 1, 'dress': 1}),
 Counter({'puma': 1, 'inspired': 1, 'terno': 1}),
 Counter({'belly': 1, 'support': 1, 'binder': 1}),
 Counter({'for': 1, 'live': 1, 'selling': 1, 'check': 1, 'out': 1, 'only': 1}),
 Counter({'nike': 1, 'lebron': 1, 'shoes': 1, 'for': 1, 'men': 1}),
 Counter({'qqs': 1,
          'wild': 1,
          'korean': 1,
          'breatable': 1,
          'casual': 1,
          'womens': 1,
          'shoes': 1}),
 Counter({'over': 1,
          'door': 1,
          'hook': 1,
          'lattfattlig': 1,
          'by': 1,
          'ikea': 1,
          'of': 1,
          'sweden': 1}),
 Counter({'forever': 1, 'preloved': 1, 'romper': 1}),
 Counter({'the': 1,
          'beuatiful': 1,
          'london': 1,
          'long': 1,
          'sleeve': 1,
          'smooth': 1,
          'ang': 1,
          'tela': 1}),
 Counter({'summer': 1, 'sandals': 1}),
 Counter({'one': 1, 'sided': 1, 'sleeve': 1, 'top': 1}),
 Counter({'black': 1,
          'skinny': 1,
          'jeans': 1,
          'pants': 1,
          'for': 1,
          'men': 1,
          'stretchable': 1,
          'denim': 1}),
 Counter({'onion': 1,
          'garlic': 1,
          'chopper': 1,
          'slicer': 1,
          'with': 1,
          'free': 1,
          'kitchen': 1,
          'towel': 1}),
 Counter({'jasmine': 1,
          'floral': 1,
          'design': 1,
          'backless': 1,
          'one': 1,
          'piece': 1}),
 Counter({'korean': 1, 'dress': 1, 'pesos': 1}),
 Counter({'overlap': 1, 'romper': 1}),
 Counter({'zoro': 1, 'shirt': 1}),
 Counter({'preloved': 1,
          'tom': 1,
          'and': 1,
          'jerry': 1,
          'rubbershoes': 1,
          'size': 1}),
 Counter({'assorted': 1,
          'women': 1,
          'long': 1,
          'wallet': 1,
          'zipper': 1,
          'wristlet': 1}),
 Counter({'rose': 1,
          'quartz': 1,
          'infinity': 1,
          'good': 1,
          'luck': 1,
          'bracelet': 1}),
 Counter({'fubu': 1, 'queens': 1, 'roundneck': 1, 'jersey': 1, 'knits': 1}),
 Counter({'hanging': 1, 'multi': 1, 'storage': 1, 'mesh': 1, 'bag': 1}),
 Counter({'tl': 1, 'red': 1, 'top': 1}),
 Counter({'new': 1, 'design': 1, 'for': 1}),
 Counter({'backless': 1,
          'and': 1,
          'brassier': 1,
          'tube': 1,
          'top': 1,
          'sexy': 1,
          'outfit': 2,
          'performer': 1}),
 Counter({'as': 1,
          'elegant': 1,
          'jumpsuit': 1,
          'plain': 1,
          'strap': 1,
          'sleeveless': 1}),
 Counter({'us': 1, 'branded': 1, 'ladies': 1, 't': 1, 'shirts': 1}),
 Counter({'fila': 1, 'slippers': 1}),
 Counter({'lipstick': 1, 'organiser': 1}),
 Counter({'chic': 1, 'floral': 1, 'maxi': 1, 'dress': 1}),
 Counter({'new': 1, 'arrival': 1, 'black': 1, 'pink': 1}),
 Counter({'s': 1,
          'j': 1,
          'gold': 1,
          'plated': 1,
          'high': 1,
          'quality': 1,
          'everyday': 1,
          'use': 1,
          'fashionable': 1,
          'with': 1}),
 Counter({'kurstenshop': 1,
          'bedsheet': 1,
          'poly': 1,
          'cotton': 1,
          'mickey': 1,
          'mouse': 1,
          'polkadots': 1,
          'design': 1}),
 Counter({'christha': 1,
          's': 1,
          'fine': 1,
          'italian': 1,
          'jewelries': 1,
          'italy': 1,
          'white': 1,
          'gold': 1,
          'trio': 1,
          'heart': 1,
          'stud': 1,
          'earrings': 1,
          'with': 1,
          'diamond': 1,
          'stones': 1}),
 Counter({'black': 1, 'mesh': 1, 'leggings': 1}),
 Counter({'bangkok': 1, 'gold': 1, 'bracelet': 1}),
 Counter({'nkd': 1,
          'korean': 1,
          'fashion': 1,
          'sally': 1,
          'floral': 1,
          'buckle': 1,
          'skorts': 1}),
 Counter({'preloved': 1, 'bohemian': 1, 'dress': 1}),
 Counter({'motorcycle': 1, 'horn': 1, 'harness': 1, 'with': 1, 'selector': 1}),
 Counter({'set': 1, 'ltaly': 1, 'sterling': 1, 'silver': 1}),
 Counter({'popshop': 1,
          'ph': 1,
          'safety': 1,
          'shorts': 1,
          'women': 1,
          'lady': 1,
          'fashion': 1,
          'pants': 1,
          'leggings': 1}),
 Counter({'roxy': 1, 'rubber': 1, 'slippers': 1}),
 Counter({'canvas': 1,
          'half': 1,
          'shoes': 1,
          'for': 1,
          'women': 1,
          'add': 1,
          'size': 1}),
 Counter({'prelove': 1, 'branded': 1, 'ukay': 1, 'from': 1, 'u': 1, 's': 1}),
 Counter({'peppa': 1, 'pig': 1, 'loot': 1, 'bags': 1}),
 Counter({'sexy': 1, 'korean': 1, 'dress': 1, 'for': 1, 'sale': 1}),
 Counter({'fd': 1, 'assorted': 1, 'mini': 1, 'dress': 1}),
 Counter({'classic': 1,
          'bodycon': 1,
          'ringer': 1,
          'dress': 1,
          'thick': 1,
          'fabric': 1}),
 Counter({'rimshot': 1, 'drumsticks': 1, 't': 1, 'shirt': 1}),
 Counter({'formal': 1, 'tube': 1, 'dress': 1}),
 Counter({'marikina': 1, 'ladies': 1, 'simple': 1, 'cut': 1, 'strap': 1}),
 Counter({'korean': 1, 'sock': 1}),
 Counter({'authentic': 1, 'mk': 1, 'runway': 1, 'chronograph': 1, 'watch': 1}),
 Counter({'free': 1,
          'size': 1,
          'brandnew': 1,
          'fitted': 1,
          'dress': 1,
          'color': 1,
          'black': 1,
          'and': 1,
          'white': 1}),
 Counter({'mr': 1, 'kleenkicks': 1, 'ready': 1, 'to': 1, 'use': 1}),
 Counter({'seiko': 1, 'vintage': 1, 'women': 1, 's': 1, 'watch': 1}),
 Counter({'li': 1,
          'ion': 2,
          'nipple': 1,
          'head': 1,
          'lithium': 1,
          'made': 1,
          'in': 1,
          'china': 1}),
 Counter({'thrifted': 1, 'black': 1, 'blazer': 1}),
 Counter({'bcbg': 1, 'maxazaria': 1, 'printed': 1, 'shift': 1, 'dress': 1}),
 Counter({'officewear': 1, 'blouse': 1, 'preloved': 1}),
 Counter({'gown': 1, 'cowlneck': 1, 'metallic': 1, 'gold': 1}),
 Counter({'nba': 1,
          'dallas': 1,
          'maverick': 1,
          'black': 1,
          'gold': 1,
          'shirt': 1}),
 Counter({'cute': 1, 'design': 1, 'authentic': 1, 'silver': 1, 'earrings': 1}),
 Counter({'polo': 1, 'shirt': 1, 'for': 1, 'mens': 1, 'cotton': 1}),
 Counter({'breastfeeding': 1, 'bra': 1, 'size': 1}),
 Counter({'elf': 1, 'ears': 1, 'nude': 1, 'color': 1, 'cosplay': 1}),
 Counter({'timing': 1,
          'belt': 1,
          'for': 1,
          'kia': 1,
          'picanto': 1,
          'getz': 1,
          'sta': 1,
          'fe': 1}),
 Counter({'polka': 1,
          'dot': 1,
          'crew': 1,
          'socks': 2,
          'country': 1,
          'foot': 1,
          'made': 1,
          'in': 1,
          'korea': 1}),
 Counter({'sandals': 1, 'brown': 1}),
 Counter({'nike': 1, 'air': 1, 'relentless': 1}),
 Counter({'household': 1,
          'rotary': 1,
          'high': 1,
          'sensitive': 1,
          'water': 2,
          'meter': 2,
          'drip': 1}),
 Counter({'long': 1,
          'floral': 1,
          'dress': 1,
          'for': 1,
          'sunday': 1,
          'occasions': 1,
          'all': 1,
          'sizes': 1,
          'available': 1}),
 Counter({'new': 1, 'lady': 1, 'white': 1, 'shoes': 1}),
 Counter({'sleeveless': 1,
          'maroon': 1,
          'top': 1,
          'terno': 2,
          'pants': 2,
          'casual': 1,
          'ootd': 1,
          'wear': 1}),
 Counter({'adventure': 1, 'awaits': 1, 'enamel': 1, 'cup': 1, 'sartin': 1}),
 Counter({'wall': 1, 'decals': 1, 'sticker': 1, 'music': 1, 'note': 1}),
 Counter({'xs': 1,
          'knit': 1,
          'preloved': 1,
          'sleeveless': 1,
          'plains': 1,
          'and': 1,
          'prints': 1}),
 Counter({'for': 1, 'him': 1, 'lev': 1, 's': 1, 'embroid': 1}),
 Counter({'computer': 1,
          'glasses': 1,
          'anti': 1,
          'blue': 1,
          'light': 1,
          'eyeglasses': 1}),
 Counter({'qoncept': 1,
          'furniture': 1,
          'layer': 1,
          'drawer': 1,
          'wood': 1,
          'filing': 1,
          'cabinet': 1}),
 Counter({'forever': 1, 'legging': 1, 's': 1, 'overrun': 1}),
 Counter({'jy': 1,
          'fashion': 1,
          'rose': 1,
          'gold': 1,
          'diamond': 1,
          'necklace': 1}),
 Counter({'onsale': 1, 'high': 1, 'waist': 1, 'shorts': 1}),
 Counter({'tupperware': 1, 'fridgemate': 1, 'set': 1}),
 Counter({'women': 1,
          'v': 1,
          'neck': 1,
          'short': 1,
          'sleeve': 1,
          'blouse': 1,
          'casual': 1,
          'top': 1}),
 Counter({'floral': 1,
          'embroidered': 1,
          'soft': 1,
          'denim': 1,
          'long': 1,
          'sleeves': 1}),
 Counter({'ladies': 1,
          'sexy': 1,
          'top': 1,
          'long': 1,
          'sleeve': 1,
          'with': 1,
          'embroidery': 1,
          'details': 1}),
 Counter({'ll': 1,
          'new': 1,
          'korean': 1,
          'lazy': 1,
          'microfiber': 1,
          'leather': 1,
          'panel': 1,
          'shoes': 1}),
 Counter({'canister': 1, 'set': 1}),
 Counter({'irregular': 1,
          'earrings': 1,
          'simple': 1,
          'wild': 1,
          'earring': 1}),
 Counter({'cement': 1, 'mixer': 1}),
 Counter({'racing': 1,
          'flag': 1,
          'size': 1,
          'inches': 1,
          'printed': 1,
          'cars': 1}),
 Counter({'large': 1, 'denim': 1, 'jumperpants': 1}),
 Counter({'breaking': 1,
          'news': 1,
          'i': 1,
          'don': 1,
          't': 1,
          'care': 1,
          'tee': 1,
          'momshies': 1}),
 Counter({'quality': 1, 'clothes': 1}),
 Counter({'backless': 1, 'floral': 1, 'dress': 1}),
 Counter({'white': 1,
          'justees': 1,
          't': 1,
          'shirt': 1,
          'happy': 1,
          'tshirt': 1,
          'for': 1,
          'old': 1,
          'girl': 1}),
 Counter({'universal': 1,
          'rocker': 1,
          'switch': 1,
          'on': 1,
          'off': 1,
          'with': 1,
          'light': 1,
          'v': 1,
          'style': 1}),
 Counter({'wood': 1, 'hand': 1, 'saw': 1, 'lagari': 1, 'lagare': 1}),
 Counter({'supreme': 1, 'flat': 1, 'shoes': 1, 'for': 1, 'women': 1}),
 Counter({'korean': 1, 'oversized': 1, 'tshirts': 1}),
 Counter({'denim': 1, 'maternity': 1, 'dress': 1}),
 Counter({'classy': 1, 'stripes': 1, 'short': 1, 'dress': 1}),
 Counter({'just': 1}),
 Counter({'yzmi': 1,
          'best': 1,
          'selling': 1,
          'stretchable': 1,
          'skinny': 1,
          'jeans': 1,
          'for': 1,
          'men': 1}),
 Counter({'grey': 1,
          'high': 1,
          'performance': 1,
          'rtv': 1,
          'silicone': 1,
          'sealant': 1}),
 Counter({'fashion': 1, 'tukong': 1}),
 Counter({'original': 1, 'freego': 1, 'polo': 1, 'shirt': 1}),
 Counter({'callie': 1, 'sleeveless': 1, 'top': 1}),
 Counter({'bobson': 1,
          'low': 1,
          'waist': 1,
          'skinny': 1,
          'tapered': 1,
          'non': 1,
          'denim': 1,
          'pants': 1}),
 Counter({'baymax': 1, 'long': 1, 'back': 1, 'shirt': 1}),
 Counter({'dickies': 1, 'branded': 1, 'tshirt': 1, 'for': 1, 'ladies': 1}),
 Counter({'thsirt': 1}),
 Counter({'blue': 1, 'denim': 1, 'romper': 1, 'for': 1, 'ootd': 1}),
 Counter({'striped': 1, 'wide': 1, 'leg': 1, 'pants': 1}),
 Counter({'korean': 1,
          'high': 1,
          'quality': 1,
          'white': 1,
          'shoes': 2,
          'rubber': 1}),
 Counter({'flip': 1, 'flop': 1, 'unisex': 1, 'slipper': 1}),
 Counter({'scato': 1,
          'ladies': 1,
          'slip': 1,
          'on': 1,
          'canvas': 1,
          'sneakers': 1}),
 Counter({'boelter': 1,
          'north': 1,
          'face': 1,
          'foldable': 1,
          'water': 1,
          'bottle': 1}),
 Counter({'chevkout': 1, 'for': 1, 'joenard': 1}),
 Counter({'chezkajose': 1, 'checkout': 1, 'link': 1}),
 Counter({'slimfit': 1,
          'rashguard': 1,
          'one': 1,
          'piece': 1,
          'swimsuit': 1,
          'swimwear': 1,
          's': 1,
          'xxl': 1}),
 Counter({'match': 1, 'teacher': 1, 'rule': 1, 'shirt': 1}),
 Counter({'single': 1, 'cartoon': 1, 'character': 1, 'bedsheet': 1}),
 Counter({'eraseheads': 1, 'face': 1, 'shirt': 1}),
 Counter({'lw': 1,
          'baby': 1,
          'g': 1,
          'watch': 3,
          'for': 1,
          'kids': 1,
          'cod': 1,
          'analog': 1,
          'sport': 1}),
 Counter({'parker': 1,
          'two': 1,
          'piece': 1,
          'padded': 1,
          'bikini': 1,
          'tc': 1}),
 Counter({'candy': 1,
          'pants': 1,
          'crepe': 1,
          'fabric': 1,
          'lowest': 1,
          'price': 1}),
 Counter({'v': 1, 'neck': 1, 'longsleeve': 1, 'for': 1, 'men': 1}),
 Counter({'cod': 1,
          'royal': 1,
          'blue': 1,
          'skinny': 1,
          'tattered': 1,
          'women': 1,
          's': 1,
          'pants': 1}),
 Counter({'front': 1, 'shock': 1, 'telescopic': 1, 'assy': 1, 'for': 1}),
 Counter({'multi': 1, 'functional': 1, 'rack': 1}),
 Counter({'ngk': 1,
          'spark': 1,
          'plug': 1,
          'for': 1,
          'ford': 1,
          'fiesta': 1,
          'and': 1,
          'ecosport': 1,
          'set': 1,
          'of': 1}),
 Counter({'polka': 1,
          'dot': 1,
          'paper': 1,
          'plates': 1,
          'party': 1,
          'supplies': 1}),
 Counter({'sweet': 1, 'pea': 1, 'iwag': 1, 'beeswax': 1, 'candle': 1}),
 Counter({'ocean': 1,
          'glassware': 1,
          'madison': 1,
          'margarita': 1,
          'oz': 1,
          'set': 1,
          'of': 1}),
 Counter({'men': 1,
          's': 1,
          'shirt': 1,
          'for': 1,
          'only': 1,
          'pesos': 1,
          'paubos': 1,
          'sale': 1,
          'korean': 1,
          'bale': 1}),
 Counter({'tuosen': 1,
          'mm': 1,
          'long': 1,
          'nose': 1,
          'stainless': 1,
          'steel': 1,
          'pliers': 1,
          'professional': 1}),
 Counter({'sleep': 1,
          'women': 1,
          'sexy': 1,
          'slim': 1,
          'panties': 1,
          'ku': 1}),
 Counter({'casual': 1, 'shirt': 1, 'for': 1, 'me': 1}),
 Counter({'vc': 1, 'korean': 1, 'slip': 1, 'ons': 1}),
 Counter({'korean': 1,
          'basic': 1,
          'lady': 1,
          'pants': 1,
          'black': 1,
          'jeans': 1,
          'maong': 1}),
 Counter({'wood': 1, 'carved': 1, 'laughing': 1, 'buddha': 1}),
 Counter({'preloved': 1, 'white': 1, 'outer': 1, 'mesh': 1, 'dress': 1}),
 Counter({'lasenza': 1, 'overrun': 1, 'bra': 1, 'amd': 1, 'panty': 1}),
 Counter({'jos': 1, 'a': 1, 'bank': 1, 'men': 1, 's': 1, 'blazer': 1}),
 Counter({'sdadsadsad': 1}),
 Counter({'air': 1,
          'jordan': 1,
          'xxxiv': 1,
          'blue': 1,
          'red': 1,
          'white': 1,
          'high': 1,
          'men': 2,
          's': 2,
          'sneakers': 1,
          'sports': 1,
          'shoes': 2,
          'athletic': 1,
          'basketball': 1}),
 Counter({'striped': 1, 'top': 1}),
 Counter({'caflon': 1,
          'crescent': 1,
          'moon': 1,
          'shape': 1,
          'sterilized': 1,
          'hypo': 1,
          'allergenic': 1}),
 Counter({'rudy': 1, 'project': 1, 'prescription': 1, 'eyewear': 1}),
 Counter({'jen': 1,
          'style': 1,
          'eyewear': 1,
          'half': 1,
          'rim': 1,
          'eyeglasses': 1,
          'reading': 1,
          'glasses': 1,
          'glass': 1,
          'for': 1,
          'men': 1,
          'and': 1,
          'women': 1,
          'eyeglass': 1}),
 Counter({'screwdriver': 1, 'philip': 1, 'nm': 1}),
 Counter({'paradise': 1, 'bridge': 1}),
 Counter({'cash': 1,
          'on': 1,
          'delivery': 1,
          'chris': 1,
          'skort': 1,
          'shorts': 1,
          'skirt': 1}),
 Counter({'checkout': 1, 'here': 1, 'link': 1}),
 Counter({'raglan': 1, 'sleeve': 1, 'drawstring': 1, 'neck': 1, 'hoodie': 1}),
 Counter({'detective': 1, 'conan': 1, 'mini': 1, 'pillow': 1, 'x': 1}),
 Counter({'rashguard': 1, 'aloha': 1}),
 Counter({'maridel': 1,
          'miner': 1,
          'dress': 1,
          'cod': 1,
          'no': 1,
          'cancellation': 1}),
 Counter({'bait': 1, 'x': 1, 'doreamon': 1, 'logo': 1, 'tee': 1, 'black': 1}),
 Counter({'plus': 1, 'size': 1, 'offshoulder': 1, 'shoulder': 1, 'dress': 1}),
 Counter({'authentic': 1, 'crocs': 1, 'shoes': 1}),
 Counter({'jjs': 1,
          'colorful': 1,
          'synthetic': 1,
          'dish': 1,
          'and': 1,
          'kitchen': 1,
          'cloth': 1}),
 Counter({'round': 1,
          'cut': 1,
          'zircon': 1,
          'cushion': 1,
          'halo': 1,
          'ring': 1}),
 Counter({'brandnew': 1, 'mermaird': 1, 'cut': 1, 'skirt': 1}),
 Counter({'terno': 1, 'inner': 1, 'included': 1}),
 Counter({'sleeveless': 1, 'dotted': 1, 'collar': 1, 'top': 1}),
 Counter({'selena': 1, 'maxi': 1, 'dress': 1}),
 Counter({'chocolate': 1, 'brand': 1, 'printed': 1, 'shirt': 1}),
 Counter({'cod': 1, 'pvc': 1, 'wallpaper': 1, 'for': 1, 'sale': 1}),
 Counter({'clearance': 1,
          'sale': 1,
          'fd': 1,
          'bed': 1,
          'sheet': 1,
          'size': 1,
          'family': 1,
          'x': 1}),
 Counter({'central': 1, 'lock': 1, 'alarm': 1}),
 Counter({'succulents': 1, 'and': 1, 'cactus': 1}),
 Counter({'royu': 1,
          'classic': 1,
          'series': 1,
          'doorbell': 1,
          'switch': 1,
          'gang': 1}),
 Counter({'buttons': 1,
          'jeans': 1,
          'high': 1,
          'waist': 1,
          'pants': 1,
          'skinny': 1,
          'stretchable': 1}),
 Counter({'mary': 1, 'panty': 1, 'boyleg': 1, 'cotton': 1}),

In [22]:
all_sample_vectors = []
for n in tqdm(range(len(translation_result))):
    all_sample_vectors.append(text_to_vector(translation_result[n]))

100%|███████████████████████████████████████████████████████████████████████| 222952/222952 [00:05<00:00, 44411.88it/s]

In [23]:
len(all_sample_vectors)

222952

Parallel mini-batch processing of translation by Google translation API

In [33]:
doc = []
for j in tqdm(range(120000,122000)): #set your mini-batch range here
    cosine_similarity = []
    vector1 = all_sample_vectors[j]
    for i in range(len(all_sentences)):
        vector2 = all_sentences_vectors[i]
        cosine_similarity.append(get_cosine(vector1, vector2))
    doc.append([filtered_train_tcn['product_title_tokenized'].iloc[j], translation_result[j], all_sentences.iloc[cosine_similarity.index(max(cosine_similarity))], max(cosine_similarity)])

print('Cosine Similarity calculation completed')

100%|████████████████████████████████████████████████████████████████████████████| 2000/2000 [1:56:34<00:00,  3.50s/it]

Cosine Similarity calculation completed

In [34]:
df = pd.DataFrame(doc, columns = ['Original','Translated','Matched','Cosine_sim'])
df.to_csv('train_matched64.csv', index=False)

Import script to combine all csv files

In [1]:
import os
import glob
import pandas as pd
os.chdir("./to_be_combined")

In [2]:
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

In [3]:
os.getcwd()

'E:\\Users\\Yee Lee\\Documents\\MITB\\CS605 NLP for Smart Assistants\\Translation project\\to_be_combined'

In [4]:
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "../preprocessed/train_matched_combined.csv", index=False, encoding='utf-8-sig')